### ISSUE TITLE
Fees need to be displayed to end-user

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#110]
We also need to make a separate call to retrieve the fees associated w/ the filing.

it's something that happens before we submit.

It's something already implemented in the proxy server. Not sure if it's in the Python side yet though.

**Comment by nonprofittechy** [comment]
#13

**Comment by nonprofittechy** [comment]
@BryceStevenWilley I am trying to submit a calculateFilingFees query and I get back:

`{​‘value’: ‘PaymentID is empty. This is a required Filing element.’, ‘id’: None, ‘metadata’: [], ‘linkMetadata’: []}​`

It looks like we ask for tyler_payment_id, and I can see in the proxy server side it translates that into PaymentID in at least one place, but I'm not fully sure how it works. I didn't see any direct references to PaymentID anywhere.

I am guessing I could copy the value of tyler_payment_id into PaymentID​​​​​​​ and it would work--but what's the right fix here?

**Comment by BryceStevenWilley** [comment]
Sorry about that, https://github.com/SuffolkLITLab/EfileProxyServer/commit/c91c050026e19964fd21785a5a180d9d7cd5e893 is on the live server now and should have a fix for that, but honestly the easiest way to test is what you have setup so far, since it requires a full DA interview. Let me know if it's working
