### ISSUE TITLE
Turn on "prevent_going_back()" before we submit for certification

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#115]
we could just add a prevent_going_back(). If there's a check on the proxy server already, no need to add that complexity though.

**Comment by BryceStevenWilley** [comment]
There isn't a check on the proxy server (not sure the best way to handle that, maybe check for the session id in the docassemble JSON?). There a `prevent_going_back()` in (https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/9f80c6a4ecd6706fb1813e0d0d82e81f30fb2ab3/docassemble/EFSPIntegration/data/questions/efiling_integration.yml#L297), but commented out because it saves a lot of development time on the proxy server to just go back and resubmit if there's some bug I'm trying to track down. We can definitely get rid of that at some point. 

We could also have a "resubmit" button if the submission failed for any reason? But that gets tricky because there could be something that goes wrong after the Tyler submission (i.e. our user transaction stuff going wrong), that would still allow a duplicate submission.

**Comment by nonprofittechy** [comment]
OK pre-submission let's just turn this back on then. i think it's fair to have the certification test require the tester to start over again from the beginning, even if it's not the final UX we want.

**Comment by BryceStevenWilley** [comment]
Turned back on with https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/commit/b3b6106471648b48591bb6e0951ebceb83b7a72f
