### ISSUE TITLE
Refactor/cleanup "any optional services" question

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#116]
1. The question is per-document, which isn't clear in the question yet.
2. It should be a checklist instead of a gathered list.

**Comment by BryceStevenWilley** [comment]
We aren't using these too much in existing interviews, so pushing to post 1.0. The per-document question part is fixed, but we need to think more about using a checklist instead of a gathered list. Most optional services are "multiple", so you can get 0, 1, 2, etc of each of them. Additionally, for some filings, there are as many as 23 different services that they can get, which is definitely a lot of check boxes, so we need to do something smarter than just dumping all of the check boxes on a single page.
