### ISSUE TITLE
Hide "suffix" on all name fields

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#45]
Tyler doesn't know about name suffixes, so we shouldn't ever display them, unless we do something to handle in the background

**Comment by nonprofittechy** [comment]
Will need to copy in and customize the name questions for now. It may be worth adding a global configuration option in AssemblyLine upstream later though.

Unless @BryceStevenWilley  you have an idea for which field a suffix should go into? Should we add it to the last name?

**Comment by BryceStevenWilley** [comment]
We're talking about for Service Contacts, Users, and the other admin ones, right? Tyler does have suffixes for party types, but they're different from ours, and (strangely) can still differ by court. Added an example below. 

For the Users and attorneys I think it could safely be added to the Last name. For service contacts I'm not sure, since I don't know how well the Tyler search works and it only matches full + exact names, and if adding a suffix to a last name where it's not expected would make the service contact unsearchable. 

 CPA
 DC
 DDS
 DO
 DVM
 Esq
 II
 III
 IV
 JD
 Jr
 LPA
 LPN
 MA
 MD
 MSW
 PhD
 RN
 Sr
 V
 VI

**Comment by nonprofittechy** [comment]
Got it, that's familiar now. I forgot we discussed that a few months ago.

For now I'll just remove the `suffix` field, and people will need to change their name to fit existing fields. At least it will be predictable--better than discarding the `suffix` field.
