### ISSUE TITLE
Update Global Payment Account

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#79]
After entering a global payment account id after being prompted to, I am redirected to the admin page without the option to update anything.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley I thought this was a minor bug but now I'm noticing when I add a global payment account, it's not actually marked as global anywhere in the case return.

I'm also thinking that we actually don't need the separate call to Update Global Payment account because it's merged into the same REST call--is that right?

**Comment by BryceStevenWilley** [comment]
Lots of changes happened since I last saw this issue, but I went through and fixed a few issues with updating global payments, should be all good now.
